In [1]:
import pyterrier as pt
if not pt.started():
  pt.init()

C:\Users\Fortu\AppData\Local\Temp\ipykernel_10624\1742394333.py:2: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():
Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.10 (build: craigm 2024-08-22 17:33), helper_version=0.0.8]
C:\Users\Fortu\AppData\Local\Temp\ipykernel_10624\1742394333.py:3: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [6]:
files = pt.io.find_files("./wp")
indexer = pt.TRECCollectionIndexer('c:/Users/Fortu/Downloads/Aut2024/Info 376/wp_index', verbose=True, blocks=False)
indexref = indexer.index(files)
index = pt.IndexFactory.of(indexref)
print(index.getCollectionStatistics().toString())

2files [00:00,  4.87files/s]

12:01:22.162 [main] WARN org.terrier.structures.indexing.Indexer -- Adding an empty document to the index (wikipedia108 short) - further warnings are suppressed
12:01:23.732 [main] WARN org.terrier.structures.indexing.Indexer -- Indexed 4 empty documents

2files [00:02,  1.27s/files]

Number of documents: 632
Number of terms: 28698
Number of postings: 161541
Number of fields: 0
Number of tokens: 282899
Field names: []
Positions:   false

In [7]:
import pandas as pd

In [8]:
queries = pd.DataFrame([["q1","president"], ["q2","new orleans"]], columns=["qid","query"])

queries

  qid        query
0  q1    president
1  q2  new orleans

In [10]:
index = pt.IndexFactory.of("c:/Users/Fortu/Downloads/Aut2024/Info 376/wp_index/data.properties")
tf_idf = pt.BatchRetrieve(index, wmodel="TF_IDF")

tf_idf.transform(queries)

C:\Users\Fortu\AppData\Local\Temp\ipykernel_10624\718701742.py:2: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  tf_idf = pt.BatchRetrieve(index, wmodel="TF_IDF")

    qid  docid                docno  rank     score        query
0    q1     83    wikipedia84 short     0  3.658845    president
1    q1    627  wikipedia3873 short     1  3.644220    president
2    q1    570  wikipedia3816 short     2  3.626854    president
3    q1    614  wikipedia3860 short     3  3.473254    president
4    q1    386  wikipedia3632 short     4  3.471778    president
..   ..    ...                  ...   ...       ...          ...
351  q2    219   wikipedia220 short   286  0.744187  new orleans
352  q2    531  wikipedia3777 short   287  0.743630  new orleans
353  q2    621  wikipedia3867 short   288  0.738108  new orleans
354  q2    485  wikipedia3731 short   289  0.718889  new orleans
355  q2    619  wikipedia3865 short   290  0.344921  new orleans

[356 rows x 6 columns]

In [11]:
bm25 = pt.BatchRetrieve(index, wmodel="BM25")
bm25.transform(queries)

C:\Users\Fortu\AppData\Local\Temp\ipykernel_10624\2873046682.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  bm25 = pt.BatchRetrieve(index, wmodel="BM25")

    qid  docid                docno  rank     score        query
0    q1     83    wikipedia84 short     0  6.105045    president
1    q1    627  wikipedia3873 short     1  6.080642    president
2    q1    570  wikipedia3816 short     2  6.051665    president
3    q1    614  wikipedia3860 short     3  5.795373    president
4    q1    386  wikipedia3632 short     4  5.792911    president
..   ..    ...                  ...   ...       ...          ...
351  q2    219   wikipedia220 short   286  0.187113  new orleans
352  q2    531  wikipedia3777 short   287  0.186973  new orleans
353  q2    621  wikipedia3867 short   288  0.185585  new orleans
354  q2    485  wikipedia3731 short   289  0.180752  new orleans
355  q2    619  wikipedia3865 short   290  0.086725  new orleans

[356 rows x 6 columns]

In [12]:
Hiemstra = pt.BatchRetrieve(index, wmodel="Hiemstra_LM")
Hiemstra.transform(queries)

C:\Users\Fortu\AppData\Local\Temp\ipykernel_10624\3653420691.py:1: DeprecationWarning: Call to deprecated class BatchRetrieve. (use pt.terrier.Retriever() instead) -- Deprecated since version 0.11.0.
  Hiemstra = pt.BatchRetrieve(index, wmodel="Hiemstra_LM")

    qid  docid                docno  rank     score        query
0    q1    570  wikipedia3816 short     0  3.021607    president
1    q1     83    wikipedia84 short     1  2.766767    president
2    q1    627  wikipedia3873 short     2  2.755464    president
3    q1    505  wikipedia3751 short     3  2.672041    president
4    q1    441  wikipedia3687 short     4  2.409940    president
..   ..    ...                  ...   ...       ...          ...
351  q2    219   wikipedia220 short   286  0.131709  new orleans
352  q2    531  wikipedia3777 short   287  0.131526  new orleans
353  q2    621  wikipedia3867 short   288  0.129729  new orleans
354  q2    485  wikipedia3731 short   289  0.123648  new orleans
355  q2    619  wikipedia3865 short   290  0.041900  new orleans

[356 rows x 6 columns]